# Class 2: Numpy, SciPy, Pandas, Statmodes and advanced visualization


## What will we learn in this class?

* Numpy
* Pandas
* Matplotlib
* Seaborn
* Sci-py

Sources:

    Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython  by Wes McKinney


# tilulo principal
## subitutulo

$$
formula=\frac{1}{2}\delta
$$

In [1]:
import numpy as np

## Numpy

NumPy, short for Numerical Python, is the foundational package for scientific computing in Python. 
on top of NumPy. It provides, among other things:
• A fast and efficient multidimensional array object ndarray
• Functions for performing element-wise computations with arrays or mathematical
operations between arrays
• Tools for reading and writing array-based data sets to disk
• Linear algebra operations, Fourier transform, and random number generation
• Tools for integrating connecting C, C++, and Fortran code to Python


In [2]:
#coding examples
import numpy as np

In [3]:
data=np.random.randn(2, 3)
data

array([[-1.00109818,  0.07044009, -1.02516603],
       [ 0.63438484, -0.58434263, -0.45864191]])

In [4]:
#broadcasting
data * 10


array([[-10.01098182,   0.70440091, -10.25166034],
       [  6.34384838,  -5.84342626,  -4.58641907]])

In [5]:
data + data

array([[-2.00219636,  0.14088018, -2.05033207],
       [ 1.26876968, -1.16868525, -0.91728381]])

In [6]:
data+data[:,0].reshape(2,1)

array([[-2.00219636, -0.93065809, -2.02626422],
       [ 1.26876968,  0.05004221,  0.17574293]])

In [7]:
data*data

array([[1.00219757, 0.00496181, 1.0509654 ],
       [0.40244412, 0.3414563 , 0.2103524 ]])

In [8]:
data.shape

(2, 3)

In [9]:
#crear arreglos
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
arr1.shape

(5,)

In [11]:
data[:,0].shape

(2,)

In [12]:
data+data[:,0].reshape(2,1)

array([[-2.00219636, -0.93065809, -2.02626422],
       [ 1.26876968,  0.05004221,  0.17574293]])

In [13]:
data[:,0].reshape(2,1).squeeze().shape

(2,)

In [14]:
data2 = [[1, 2.0, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [15]:
arr2.dtype

dtype('float64')

In [16]:
np.zeros(10)
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
1 / arr


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [20]:
arr.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [21]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [23]:
#operacion logica
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [24]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [25]:
m1=np.array([[1., 2.], [2., 1]])
print(m1)
print(np.matmul(m1,m1))

[[1. 2.]
 [2. 1.]]
[[5. 4.]
 [4. 5.]]


In [26]:
m1*m1

array([[1., 4.],
       [4., 1.]])

In [27]:
#indexing and slicing
arr = np.arange(10)*10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
arr[5]

50

In [29]:
arr[5:8]

array([50, 60, 70])

In [30]:
arr[5:8] = 12
arr

array([ 0, 10, 20, 30, 40, 12, 12, 12, 80, 90])

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [32]:
data = np.random.randn(7, 4)
data

array([[ 1.77998565,  0.72839899,  0.91219484,  0.14724693],
       [-0.48710535,  0.08539872,  0.12700474, -0.6886856 ],
       [ 0.68855954, -1.63779496, -0.12386654, -0.04898135],
       [ 0.10681277, -0.77996196, -0.39112614,  0.3190114 ],
       [ 0.53554462, -0.84737767, -1.19891363, -0.75775915],
       [-1.4771606 ,  1.57182604,  1.62877025, -0.60554916],
       [ 0.98658569,  1.45244582, -1.03589323,  1.55180805]])

In [33]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [34]:
data[names == 'Bob']

array([[ 1.77998565,  0.72839899,  0.91219484,  0.14724693],
       [ 0.10681277, -0.77996196, -0.39112614,  0.3190114 ]])

In [35]:
data[names == 'Bob', 2:]


array([[ 0.91219484,  0.14724693],
       [-0.39112614,  0.3190114 ]])

In [36]:
data[names == 'Bob', 3]

array([0.14724693, 0.3190114 ])

In [37]:
data[names == 'Bob'][:,3]

array([0.14724693, 0.3190114 ])

As Data Scientist we will be using numpy particularly in two instances

1. Speeding pandas 
2. Creating tensors to feed our machine learning algorithms

<img src="static/img/tensor.png">




Lets see how we can create a multidimensional Tensor. For this exercise we will read csv files withouth headers and indices from 11 different assets: Microsoft, Netflix, Intel, Google, Nvidia, Amazon, Tesla,Apple, Facebook, Paypal and S&P oil and gas sector. Each file contains a time serie with 1minute bars from each stock or etf. 

For this exercise we will read each time serie individually, save it in a dictionary and the  create a 5x5x11 tensor

In [38]:
import os

file_names=[f for f in os.listdir("data/") if "nc.csv" in f]
file_names

['AAPL_Stocks__NASDAQnc.csv',
 'AMZN_Stocks__NASDAQnc.csv',
 'FB_Stocks__NASDAQnc.csv',
 'GOOG_Stocks__NASDAQnc.csv',
 'INTC_Stocks__NASDAQnc.csv',
 'MSFT_Stocks__NASDAQnc.csv',
 'NFLX_Stocks__NASDAQnc.csv',
 'NVDA_Stocks__NASDAQnc.csv',
 'PYPL_Stocks__NASDAQnc.csv',
 'QQQ_ETF__NASDAQnc.csv',
 'TSLA_Stocks__NASDAQnc.csv',
 'XLE_ETF__AMEXnc.csv']

In [39]:
os.listdir("data/")

['AAPL_Stocks__NASDAQ.csv',
 'AAPL_Stocks__NASDAQnc.csv',
 'AMZN_Stocks__NASDAQ.csv',
 'AMZN_Stocks__NASDAQnc.csv',
 'FB_Stocks__NASDAQ.csv',
 'FB_Stocks__NASDAQnc.csv',
 'GOOG_Stocks__NASDAQ.csv',
 'GOOG_Stocks__NASDAQnc.csv',
 'INTC_Stocks__NASDAQ.csv',
 'INTC_Stocks__NASDAQnc.csv',
 'MSFT_Stocks__NASDAQ.csv',
 'MSFT_Stocks__NASDAQnc.csv',
 'NFLX_Stocks__NASDAQ.csv',
 'NFLX_Stocks__NASDAQnc.csv',
 'NVDA_Stocks__NASDAQ.csv',
 'NVDA_Stocks__NASDAQnc.csv',
 'PYPL_Stocks__NASDAQ.csv',
 'PYPL_Stocks__NASDAQnc.csv',
 'QQQ_ETF__NASDAQ.csv',
 'QQQ_ETF__NASDAQnc.csv',
 'TSLA_Stocks__NASDAQ.csv',
 'TSLA_Stocks__NASDAQnc.csv',
 'XLE_ETF__AMEX.csv',
 'XLE_ETF__AMEXnc.csv']

In [40]:
file_names=[f for f in os.listdir("data/") if "nc.csv" in f]

In [41]:
from numpy import genfromtxt
arrays={}
for file in file_names:
    arrays[file]=genfromtxt("data/"+file, delimiter=',')
    print(arrays[file].shape)

(1029493, 5)
(1027391, 5)
(795631, 5)
(599181, 5)
(1029481, 5)
(1029534, 5)
(1025770, 5)
(1038832, 5)
(486964, 5)
(1040095, 5)
(959423, 5)
(1029420, 5)


In [42]:
import os
arrays["NFLX_Stocks__NASDAQnc.csv"][:5,:]

array([[7.892858e+00, 7.961429e+00, 7.885715e+00, 7.892858e+00,
        1.451520e+05],
       [7.902857e+00, 7.928572e+00, 7.894286e+00, 7.911429e+00,
        8.267000e+04],
       [7.917143e+00, 7.921429e+00, 7.898572e+00, 7.898572e+00,
        1.046000e+05],
       [7.898572e+00, 7.911429e+00, 7.894286e+00, 7.898572e+00,
        4.759900e+04],
       [7.904286e+00, 7.927144e+00, 7.892858e+00, 7.911429e+00,
        9.499600e+04]])

In [43]:
#create tensor

prices_tensor=np.zeros((5,5,12))
counter=0
for key,value in arrays.items():
    prices_tensor[:,:,counter]=value[:5,:]
    counter=counter+1

In [44]:
temp_dict={"frutas":["mango","fresa"],"verduras":["cebollas","pepinos"]}
counter=0
for key,value in temp_dict.items():
    print(counter)
    print(key)
    print("====")
    print(value)
    counter=counter+1
    


0
frutas
====
['mango', 'fresa']
1
verduras
====
['cebollas', 'pepinos']


In [45]:
prices_tensor.shape

(5, 5, 12)

In [46]:
prices_tensor[:,:,0].shape

(5, 5)

## Pandas
pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language. 

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean and process your data. In pandas, a data table is called a DataFrame.

lets check this: https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented


Lets keep working with our data and read the csv files

sources:
https://pandas.pydata.org/

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html


In [47]:
import pandas as pd
pandas_file_names=[f for f in os.listdir("data/") if "nc.csv" not in f]
print(pandas_file_names)
fin_data_df={}
for file in pandas_file_names:
    fin_data_df[file]=pd.read_csv("data/"+file, index_col="time")

['AAPL_Stocks__NASDAQ.csv', 'AMZN_Stocks__NASDAQ.csv', 'FB_Stocks__NASDAQ.csv', 'GOOG_Stocks__NASDAQ.csv', 'INTC_Stocks__NASDAQ.csv', 'MSFT_Stocks__NASDAQ.csv', 'NFLX_Stocks__NASDAQ.csv', 'NVDA_Stocks__NASDAQ.csv', 'PYPL_Stocks__NASDAQ.csv', 'QQQ_ETF__NASDAQ.csv', 'TSLA_Stocks__NASDAQ.csv', 'XLE_ETF__AMEX.csv']


In [48]:
#data is structured and easier to read
fb_data_df=fin_data_df["FB_Stocks__NASDAQ.csv"]
fb_data_df

open    high       low    close      volume
time                                                                     
2012-05-18 15:30:00+00:00   42.050   45.00   42.0000   42.230  83177720.0
2012-05-18 15:31:00+00:00   42.270   43.00   41.8300   42.010   5523794.0
2012-05-18 15:32:00+00:00   42.010   42.99   40.0000   41.400   6662136.0
2012-05-18 15:33:00+00:00   41.270   42.66   39.4400   40.940   5206776.0
2012-05-18 15:34:00+00:00   40.900   41.89   38.9100   40.250   2921595.0
...                            ...     ...       ...      ...         ...
2020-07-07 19:56:00+00:00  240.720  241.07  240.6283  240.830    129679.0
2020-07-07 19:57:00+00:00  240.845  241.35  240.8450  241.220    123966.0
2020-07-07 19:58:00+00:00  241.210  241.25  241.0600  241.105    109628.0
2020-07-07 19:59:00+00:00  241.080  241.12  240.8300  240.860    327943.0
2020-07-07 20:00:00+00:00  240.860  240.86  240.8600  240.860   1121390.0

[795631 rows x 5 columns]

In [49]:
#top rows
fb_data_df.head()

open   high    low  close      volume
time                                                             
2012-05-18 15:30:00+00:00  42.05  45.00  42.00  42.23  83177720.0
2012-05-18 15:31:00+00:00  42.27  43.00  41.83  42.01   5523794.0
2012-05-18 15:32:00+00:00  42.01  42.99  40.00  41.40   6662136.0
2012-05-18 15:33:00+00:00  41.27  42.66  39.44  40.94   5206776.0
2012-05-18 15:34:00+00:00  40.90  41.89  38.91  40.25   2921595.0

In [50]:
#bottom rows
fb_data_df.tail()

open    high       low    close     volume
time                                                                    
2020-07-07 19:56:00+00:00  240.720  241.07  240.6283  240.830   129679.0
2020-07-07 19:57:00+00:00  240.845  241.35  240.8450  241.220   123966.0
2020-07-07 19:58:00+00:00  241.210  241.25  241.0600  241.105   109628.0
2020-07-07 19:59:00+00:00  241.080  241.12  240.8300  240.860   327943.0
2020-07-07 20:00:00+00:00  240.860  240.86  240.8600  240.860  1121390.0

In [51]:
#any rows
#by number use iloc
fb_data_df.iloc[1:3]

open   high    low  close     volume
time                                                            
2012-05-18 15:31:00+00:00  42.27  43.00  41.83  42.01  5523794.0
2012-05-18 15:32:00+00:00  42.01  42.99  40.00  41.40  6662136.0

In [52]:
#by index value use loc
random_index=np.random.randint(0,fb_data_df.shape[1],2)
random_index

array([1, 1])

In [53]:

random_dates=fb_data_df.index[random_index.tolist()].values.tolist()
random_dates


['2012-05-18 15:31:00+00:00', '2012-05-18 15:31:00+00:00']

In [54]:
random_index.tolist()


[1, 1]

In [55]:
fb_data_df.loc["2020-07-07 19:58:00+00:00"]

open         241.210
high         241.250
low          241.060
close        241.105
volume    109628.000
Name: 2020-07-07 19:58:00+00:00, dtype: float64

In [56]:
indice_2=pd.to_datetime(fb_data_df.index)
indice_2

DatetimeIndex(['2012-05-18 15:30:00+00:00', '2012-05-18 15:31:00+00:00',
               '2012-05-18 15:32:00+00:00', '2012-05-18 15:33:00+00:00',
               '2012-05-18 15:34:00+00:00', '2012-05-18 15:35:00+00:00',
               '2012-05-18 15:36:00+00:00', '2012-05-18 15:37:00+00:00',
               '2012-05-18 15:38:00+00:00', '2012-05-18 15:39:00+00:00',
               ...
               '2020-07-07 19:51:00+00:00', '2020-07-07 19:52:00+00:00',
               '2020-07-07 19:53:00+00:00', '2020-07-07 19:54:00+00:00',
               '2020-07-07 19:55:00+00:00', '2020-07-07 19:56:00+00:00',
               '2020-07-07 19:57:00+00:00', '2020-07-07 19:58:00+00:00',
               '2020-07-07 19:59:00+00:00', '2020-07-07 20:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='time', length=795631, freq=None)

In [57]:
# we can also call the columns
fb_data_df.columns


Index(['open', 'high', 'low', 'close', 'volume'], dtype='object')

### Complex functions with apply

source:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html


In [58]:
df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
df

A  B
0  4  9
1  4  9
2  4  9

In [59]:
df.apply(np.sqrt)

A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [60]:
df.apply(np.sum, axis=1)

0    13
1    13
2    13
dtype: int64

In [61]:
df.apply(np.sum, axis=0)

A    12
B    27
dtype: int64

In [62]:
df.apply(lambda x: [1, 2], axis=1)

0    [1, 2]
1    [1, 2]
2    [1, 2]
dtype: object

### Pandas Data types

before going forward lets make a break to discuss the data types of pandas dataframes. In many cases the types will be naturally infered. However, when it is not the case we need to specify them, specially if we want to  use the full pandas functionality. 

Lets see what happens if we want to get all the data after 2017


In [63]:
import datetime
break_date=datetime.datetime.utcnow()-datetime.timedelta(days=500)
print(break_date)


2019-04-21 02:19:04.771263


In [64]:
type(break_date)

datetime.datetime

In [65]:
fb_data_df.dtypes

open      float64
high      float64
low       float64
close     float64
volume    float64
dtype: object

In [66]:
fb_data_df[fb_data_df.index>break_date]

TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'

In [ ]:
# ups , error our index is not a datetime index, so we need to convert it. lets do this
fb_data_df.index=pd.to_datetime(fb_data_df.index)
fb_data_df.index

In [ ]:
fb_data_df[fb_data_df.index>break_date]

In [ ]:
import pytz

break_date.replace(tzinfo=pytz.utc)


In [ ]:
fb_data_df[fb_data_df.index>break_date.replace(tzinfo=pytz.utc)]


 Pandas can work very nicely with time series and time indices. While we are using utc dates in the index and the target date, this is not obligatory. We could have requested a slice using any time zone and pandas will automatically convert. Very useful when trading across time zones. 
 
 ### Group by: split-apply-combine
 
 
 source:
 
 https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

In [ ]:
#lets see an example. lets group our data by  day of trade
fb_data_df["day_of_trade"]=[i.date() for i in fb_data_df.index]

fb_data_df.head()


In [ ]:
fb_data_df.groupby(["day_of_trade","time"]).last()

In [ ]:
#we can create operations on groups using transform. lets suppose we want to assign the last trade
#price of each trade day to each overvation

fb_data_df.iloc[:1000].groupby(["day_of_trade"])["close"].transform(lambda x: max(x))

In [ ]:
#lets check if it is right
unique_days=fb_data_df.day_of_trade.unique()
fb_data_df[fb_data_df.day_of_trade<=unique_days[0]]

In [ ]:
fb_data_df.iloc[0:1000][fb_data_df.iloc[0:1000].day_of_trade>=fb_data_df.iloc[0:1000].day_of_trade.values[-1]]

### Resampling

Instead of grouping we can ask pandas directly to resample our data. 

source:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.resample.html


In [ ]:
fb_data_df.resample("5min").mean()

### Merging

Very often when we work with pandas we dont want to use tensors but column arrangements as features. We can achieve this in many ways

In [ ]:
amazon_df=fin_data_df["AMZN_Stocks__NASDAQ.csv"]
amazon_df.index=pd.to_datetime(amazon_df.index)
print(amazon_df.shape)
print(fb_data_df.shape)

In [ ]:
amazon_df.columns=[col+"_AMZN" for col in amazon_df]
amazon_df.head()

In [ ]:
pd.concat([fb_data_df,amazon_df],axis=1)

In [ ]:
pd.concat([amazon_df,fb_data_df],axis=1)

We can also use a more advanced merge  inspired on sql joins


In [ ]:
amazon_df.merge(fb_data_df,left_index=True,right_index=True,how="left")

In [ ]:
amazon_df.merge(fb_data_df,left_index=True,right_index=True,how="inner")

In [ ]:
amazon_df.merge(fb_data_df,left_index=True,right_index=True,how="right")

In [ ]:
new_df=amazon_df.merge(fb_data_df,left_index=True,right_index=True,how="inner")[["close","close_AMZN"]].resample("1d").last().dropna()

In [ ]:
type(new_df)

### Matplolib and Seaborn

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.

Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.

Matplotlib is the standard pandas ploting library, lets see a few visualizations

sources:

https://matplotlib.org/

https://seaborn.pydata.org/

In [ ]:
amzn_merg=amazon_df.merge(fb_data_df,left_index=True,right_index=True,how="left")
missing_values=amzn_merg[amzn_merg.isnull().any(axis=1)]
missing_values

close_monthly=amzn_merg[[col for col in amzn_merg.columns if "close" in col]].resample("1m").last().dropna()
close_monthly.plot()


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline


fig, axs = plt.subplots(1, 2,figsize=(10,5))
axs[0].plot(close_monthly.close)
axs[0].title.set_text('Facebook ')
axs[0].set_ylabel("price")

axs[1].plot(np.log(close_monthly["close_AMZN"]))
axs[1].title.set_text('Amazon ')
axs[1].set_ylabel("log price")

In [ ]:

import seaborn as sns
sns.set(style="darkgrid")


In [ ]:

g=sns.pairplot(np.log(close_monthly).diff().dropna())
g.fig.set_size_inches(7,7)

### Scipy

SciPy (pronounced “Sigh Pie”) is open-source software for mathematics, science, and engineering.

Most of the libraries that you will use,  provide you with optimzed solutions. For the cases that when you need a simple multi porpuse optimizer you can use scipy.

The scipy.optimize package provides several commonly used optimization algorithms. A detailed listing is available: scipy.optimize (can also be found by help(scipy.optimize)).

The module contains:

    Unconstrained and constrained minimization of multivariate scalar functions (minimize) using a variety of algorithms (e.g. BFGS, Nelder-Mead simplex, Newton Conjugate Gradient, COBYLA or SLSQP)
    Global (brute-force) optimization routines (e.g., anneal, basinhopping)
    Least-squares minimization (leastsq) and curve fitting (curve_fit) algorithms
    Scalar univariate functions minimizers (minimize_scalar) and root finders (newton)
    Multivariate equation system solvers (root) using a variety of algorithms (e.g. hybrid Powell, Levenberg-Marquardt or large-scale methods such as Newton-Krylov).



source:

https://docs.scipy.org/doc/scipy/reference/index.html

### The Good, The Bad and The Ugly

The Good: Pandas can help us working with tabular multidimensional data in a simpler and declarative way. 

The Bad: When working with big data ( millions of rows and several columns) We cant use dataframes as they are  loaded in memory. This implies that pandas methods may not run or raise exception when trying to combine/aggregate big data. 

The Ugly: Pandas can be very slow if using the wrong method (and in general is slower than Numpy) if what you are looking is speed then you may need to work with Numpy arrays or even more you will need to use Cython. 

Lets look at an example:

From  Chapter 5 of the Advances in Financial Machine Learning (AFML) by Dr. Marcos Lopez de Prado therein he discusses fractionally differencing the time series (as opposed to integer differencing). A fractionally differentiated series is stationary but also has high correlation with the original series. Since a fractionally differenced series retains the memory of the original series (as indicated by the high correlation)



Why Fractional Differentiation?

Inferential analysis of data comprises of using a sample of data to describe the characteristics such as mean and standard deviation of a feature of a population. Consider studying heights of men and women in North America or stock prices. For such an analysis and inference to be accurate, it is necessary that the underlying data generation process to remain constant. In the context of finance, the mean return and variance of those returns should be time-invariant (or not change with time). If the underlying process changes as a result of shift in regime, it would be hard to predict expected risk and return of that stock for a future date. A similar requirement exists in the case of supervised machine learning (SML). SML is a process of learning a function that maps an input to an output based on known input-output examples. In this learning process, each example is a pair consisting of an input object (often a vector or features) and an output (or a signal). The supervised learning algorithm analyzes the training examples and infers a transformation function that can be used to map new (unseen) inputs. If the data (features, in the case of SML) are not “stationary” (in other words, their underlying data generation process changes its characteristics) then the machine learning algorithm would not be able to correctly infer the label of the new observation. Therefore, stationarity becomes a necessary condition for inferential analysis and supervised machine learning. But there is a problem here – even though making a series stationary makes inference analysis and SML easier, the series loses its memory (it probably had a trend and that trend is stripped away in the process of integer differencing). This memory is helpful in predicting where will the asset price series be next point in time. This leads to a challenge – how can one make the time series stationary while retaining its predictive power (or memory).



sources:


https://cython.org/

https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6

https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html

One of the easiest ways to make your code in pandas very slow is to loop over loc searchers.In terms of speed this is my recomendation

1. Use iloc vs loc when possible
2. If you can do your computations with iloc , then you can do also using numpy
3. When slicing a data frame, use function ```isin()``` for example
```
data[data.index.isin([date])] 
#rather than
data[data.index==date]

```
4. SQL merge is faster than pandas concatenation. but if you go for this route beware of the type of join. 


# Homework. 


The objective of this exercise is to build a class that helps us find missing data in high frequency time series. 

#### Build a class called DataHandler that initiates with a csv file path as argument
```
def DataHandler:

    def __init__(file_path):
        ...


```


#### Create a method that aggregates the data every 5 min and every 1 min for every trading day

The method should take in count all the time elapsed between the first trade observation and the last observation
even when the time bars are not present in the time series. Be careful of not including non-trading time. i.e the time series shouldnt include any time before 930 am or after 16:00 NY Time. 

for example, if the time series has the bellow data in 2010-01-04

```
2010-01-04 14:31:00+00:00    135.77
2010-01-04 14:33:00+00:00    135.32

```

it should return
```
2010-01-04 14:31:00+00:00    135.77
2010-01-04 14:32:00+00:00    Nan
2010-01-04 14:33:00+00:00    135.32

```

#### create a method that counts the  average number of NaNs per day in your time serie


#### create a method that  visualizes the "holes" the time serie by aggregation time


**NOTE: The methods should only use pandas or numpy methods. You can use for loops for debugging but final solution shoul only include pandas methods**

In [ ]:

class DataHandler:


    def __init__(self,file_path):
        """
        reads a csv file and stores it as a pandas data frame
        :param file_path:
        """

      

    def resample_to_frequnecy(self,time_frequency="5min"):
        """

        :param time_frequency:
        :return:
        """
     
        return 


    def count_nans(self,time_frequency):
        """

        :param time_frequency:
        :return:
        """
     
        return 
    
    def visualize_nans(self,time_frequency):

